### PR TITLE
Application Insights Integration Changes

### PR DESCRIPTION
**Pull request by puneetg1983**
1. Logging telemetry for connected, not connected, invalid scenarios.
2. Checking for missing access and missing write access and hiding the button.
3. Adding a link to the documentation blog when we show the Connect Button.
4. Making it easier to call AI blades from detectors via solutions.

### CODE REVIEW

**Comment by cindylovescoding** [comment]
Hey @puneetg1983,
Could you let us know what we show currently for the customers for  these scenarios?

- Application insights enabled and connected to D&S already
- Application insight not enabled for app service
- Application insight enabled but missing access to the subscription to list all the app insights instances
- Application insight enabled but invalid value in app settings 
- Application insight enabled but missing access to the instance
- Application insight enabled but missing write access to the instance

**Comment by puneetg1983** [comment]
@cindylovescoding - All these messages are in app-insights-enablement-component.html.

Are you asking for screenshot?

**Comment by cindylovescoding** [comment]
A screenshot will be helpful Puneet. Since our logic to check app insight instance is more complicated and accurate, I am trying to think what we show for all the scenarios in general and see if I could get a quick summary from you. But I guess I can read through and figure it out.

**Comment by puneetg1983** [comment]
Updating the PR shortly with all the screenshots

**Comment by puneetg1983** [comment]
image

image




image

image


image

**Pull request merged**
