### PR TITLE
Add portal session Id for diagnostic tools page

### PR DESCRIPTION
**Pull request by cindylovescoding**
Add portal session Id information for diagnostics tools page logging

### CODE REVIEW

**Review by XiaoxuHU — APPROVED** [review]

**Comment by XiaoxuHU** [comment]
Cindy, will Session Id get logged in landing page ?

**Comment by cindylovescoding** [comment]
> Cindy, Will Session Id get logged in landing page ?

Good point. Need to check that

**Comment by cindylovescoding** [comment]
> > Cindy, Will Session Id get logged in landing page ?
> 
> Good point. Need to check that

I will put another PR for that

**Comment by XiaoxuHU** [comment]
> > > Cindy, Will Session Id get logged in landing page ?
> > 
> > 
> > Good point. Need to check that
> 
> I will put another PR for that

Thank you, Cindy !

**Pull request merged**
