### PR TITLE
NetworkTroubleshooter VNet deletion flow can check if a subnet is integrated with any app

### PR DESCRIPTION
**Pull request by yifguoMSFT**
Calls checkSubnetIntegrationUsage detector to get result from Observer
image
image

### CODE REVIEW

**Comment by XiaoxuHU** [comment]
@yifguoMSFT, there is a [build exception](https://dev.azure.com/app-service-diagnostics-portal/app-service-diagnostics-portal/_build/results?buildId=8297&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=9c939e41-62c2-5605-5e05-fc3554afc9f5)

**ERROR in projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/network-checks.component.html(3,32): : Property 'onClickPreview' does not exist on type 'NetworkCheckComponent'.**

**Review by cindylovescoding — APPROVED** [review]
Hi Jeff, is this change supposed to go to production slot or preview slot（100% external traffic now）？If preview, could send a PR to ApplensRevamp branch too?
Also, we have the last payload to deploy today? Is this change target for today's deployment?

**Comment by yifguoMSFT** [comment]
> @yifguoMSFT, there is a [build exception](https://dev.azure.com/app-service-diagnostics-portal/app-service-diagnostics-portal/_build/results?buildId=8297&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=9c939e41-62c2-5605-5e05-fc3554afc9f5)
> 
> **ERROR in projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/network-checks.component.html(3,32): : Property 'onClickPreview' does not exist on type 'NetworkCheckComponent'.**

fixed

**Comment by yifguoMSFT** [comment]
> Hi Jeff, is this change supposed to go to production slot or preview slot（100% external traffic now）？If preview, could send a PR to ApplensRevamp branch too? Also, we have the last payload to deploy today? Is this change target for today's deployment?

Sure. I am not trying to deploy it today. We can deploy it later

**Review by XiaoxuHU — APPROVED** [review]

**Pull request merged**
