### PR TITLE
Enable Live chat from 9-6

### PR DESCRIPTION
**Pull request by ShekharGupta1988**
Only for Case Submission right now from 9AM to 6PM

### CODE REVIEW

**Comment by stevenernst131** [comment]
Just internal?

**Comment by ShekharGupta1988** [comment]
Internal Just for Home Page . 
I found that chat is not there on Home Page?

**Comment by stevenernst131** [comment]
Chat should only show up for case submission, I haven't integrated it into chat yet. What do you mean for 'Home Page'

**Comment by ShekharGupta1988** [comment]
Diagnose and Solve blade

**Comment by stevenernst131** [comment]
Way ahead of you :)
image
Now that flag just has to actually be used

**Comment by ShekharGupta1988** [comment]
lol.. That's cool.

Then whenever you have time, just add the live chat back on the category. :)

**Pull request merged**
