### PR TITLE
Nmallick1/No resource support for app lens

### PR DESCRIPTION
**Pull request by nmallick1**
## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Solution description
Adding support for no resource in AppLens
Authors can compile detectors with a special attribute to target their detectors and have them work for this case
## Checklist <span>&#9989;</span>
- [ ] I have looked over the diffs.
- [ ] I have run the linter to catch any errors.
- [ ] There are no errors from my changes on this branch.
- [ ] I have ensured that my changes support accessibility and can be accessed with the keyboard alone
- [ ] I have requested review on this PR.

## Screenshots After Fix (if appropriate):
image

image

### CODE REVIEW

**Review by ShekharGupta1988 — APPROVED** [review]

**Comment by ShekharGupta1988** [comment]
@nmallick1 - given the magnitude of the changes here, how do you feel about doing this deployment in phases (prob over a 2-3 days) so that there is enough baking time. Or we can enable this new code first only for test subs (but looking at the code, I am guessing it might be difficult to achieve the later)

**Comment by hforeste** [comment]
Hey @nmallick1 , can you try running Applens on your local machine in nclouds mode:

Build the UI project with
`npm run build-ncloud-applens-local`

Then launch Applens backend project with the `AppLensV3NationalClouds` launch profile simply be doing:
image

Verify that the UI is working as expected:
1. Entering app name etc
2. List Detectors
3. Execute any detector

**Comment by nmallick1** [comment]
@ShekharGupta1988 , deploying over a few days makes perfect sense.. We can deploy and keep it on staging, demo to a service, have them use it for a day or so and then once a few services have tried it, we can complete the deployment

**Comment by nmallick1** [comment]
> Hey @nmallick1 , can you try running Applens on your local machine in nclouds mode:
> 
> Build the UI project with `npm run build-ncloud-applens-local`
> 
> Then launch Applens backend project with the `AppLensV3NationalClouds` launch profile simply be doing: image
> 
> Verify that the UI is working as expected:
> 
> 1. Entering app name etc
> 2. List Detectors
> 3. Execute any detector

@hforeste ,npm run build-ncloud-applens-local exits, I do not see the server continue to run like I do in npm run applens

**Review by hforeste — APPROVED** [review]

**Pull request merged**
