### PR TITLE
Fix bug in Insight Component

### PR DESCRIPTION
**Pull request by XiaoxuHU**
Fix failed [Bug 1319](https://dev.azure.com/app-service-diagnostics-portal/app-service-diagnostics-portal/_workitems/edit/1319) due to failure when trying to pass null into  **str.trim()** in getMarkdown method

A live repo in [Applens](https://applens.azurewebsites.net/subscriptions/14548673-81fd-4315-a7eb-7eff739c6a75/resourceGroups/MyAmLINKPOC/providers/Microsoft.Web/sites/Amlink-Outlook-Addin-API/detectors/LinuxBasicWebAppInfo?startTime=2020-05-28T18:04&endTime=2020-05-29T17:49)

### CODE REVIEW

**Comment by cindylovescoding** [comment]
Hi @XiaoxuHU, this seems not fixing the stack trace below. 
I think the right fix will be doing a null track before useing .trim() in .getMarkdown() function.

Cannot read property 'trim' of null   

TypeError: Cannot read property 'trim' of null     at t.getMarkdown (https://appservice-diagnostics.azurefd.net/main.889058a79b0728d84d54.js:1:186113)     at Object.updateDirectives (https://appservice-diagnostics.azurefd.net/main.889058a79b0728d84d54.js:1:2516811)     at Object.updateDirectives (https://appservice-diagnostics.azurefd.net/main.889058a79b0728d84d54.js:1:2052443)     at Pb (https://appservice-diagnostics.azurefd.net/main.889058a79b0728d84d54.js:1:2044212)     at Nb (https://appservice-diagnostics.azurefd.net/main.889058a79b0728d84d54.js:1:2051156)     at Lb (https://appservice-diagnostics.azurefd.net/main.889058a79b0728d84d54.js:1:2050819)     at Pb (https://appservice-diagnostics.azurefd.net/main.889058a79b0728d84d54.js:1:2044234)     at Nb (https://appservice-diagnostics.azurefd.net/main.889058a79b0728d84d54.js:1:2051156)     at Lb (https://appservice-diagnostics.azurefd.net/main.889058a79b0728d84d54.js:1:2050819)     at Pb (https://appservice-diagnostics.azurefd.net/main.889058a79b0728d84d54.js:1:2044234)
--

**Comment by XiaoxuHU** [comment]
> Hi @XiaoxuHU, this seems not fixing the stack trace below.
> I think the right fix will be doing a null track before useing .trim() in .getMarkdown() function.
> 
> Cannot read property 'trim' of null
> 
> TypeError: Cannot read property 'trim' of null     at t.getMarkdown (https://appservice-diagnostics.azurefd.net/main.889058a79b0728d84d54.js:1:186113)     at Object.updateDirectives (https://appservice-diagnostics.azurefd.net/main.889058a79b0728d84d54.js:1:2516811)     at Object.updateDirectives (https://appservice-diagnostics.azurefd.net/main.889058a79b0728d84d54.js:1:2052443)     at Pb (https://appservice-diagnostics.azurefd.net/main.889058a79b0728d84d54.js:1:2044212)     at Nb (https://appservice-diagnostics.azurefd.net/main.889058a79b0728d84d54.js:1:2051156)     at Lb (https://appservice-diagnostics.azurefd.net/main.889058a79b0728d84d54.js:1:2050819)     at Pb (https://appservice-diagnostics.azurefd.net/main.889058a79b0728d84d54.js:1:2044234)     at Nb (https://appservice-diagnostics.azurefd.net/main.889058a79b0728d84d54.js:1:2051156)     at Lb (https://appservice-diagnostics.azurefd.net/main.889058a79b0728d84d54.js:1:2050819)     at Pb (https://appservice-diagnostics.azurefd.net/main.889058a79b0728d84d54.js:1:2044234)

No, this issue was due to we put **null** into the value of insight.data and then when getting the value and trying to parsing it with **trim()** inside  **getMarkdown()** , so I fixed it by parse the value into string before we put it into insight.data

**Comment by cindylovescoding** [comment]
If we have null check this won't happen either. Could you help add that to guard the logic to reference?

**Comment by XiaoxuHU** [comment]
> @XiaoxuHU If we have null check this won't happen either. Could you help add that to guard the logic to reference?

I think for now this should be good. Since this issue was caused by failed to convert null into "null" string and **`{row[valueColumnIndex]}`** will be work fine even though they pass null or undefined. If you want, I can also add into **getmarkdown()** to cover null/undefined check

**Pull request merged**
