### PR TITLE
Remove markdown border if no title is given to markdown view

### PR DESCRIPTION
**Pull request by cindylovescoding**
image

### CODE REVIEW

**Comment by hforeste** [comment]
Hey Cindy, by removing the border does it also remove the open in outlook and copy to email
image

**Comment by cindylovescoding** [comment]
Yes @hforeste , it will also remove the header templates and buttons.

**Comment by ShekharGupta1988** [comment]
Not sure how many people are actually using that feature to be honest. Cindy - you can pull that info from kusto just to check the clicks on those buttons.

It might be better to provide a way for authors to specify whether they need the container or not from authoring experience.

**Comment by hforeste** [comment]
> Yes @hforeste , it will also remove the header templates and buttons.

Why are we removing this?

**Comment by hforeste** [comment]
> Not sure how many people are actually using that feature to be honest. Cindy - you can pull that info from kusto just to check the clicks on those buttons.
> 
> It might be better to provide a way for authors to specify whether they need the container or not from authoring experience.

I am also for having this behavior where the author can decide

**Comment by ShekharGupta1988** [comment]
> > Yes @hforeste , it will also remove the header templates and buttons.
> 
> Why are we removing this?

There are scenarios where people want to just add a Title to the section of data  or some description (in markdown). (Xin wanted that for Restart analysis, Marie wanted that for few function detectors..)

The problem with Markdown rendering is anytime you use res.AddMarkdownView(..), it add those borders with buttons, even to just put a H3 tag on the page.

**Comment by cindylovescoding** [comment]
@ShekharGupta1988 @hforeste I have sent out another PR in backend to add the flag while AddMarkdownview
https://github.com/Azure/Azure-AppServices-Diagnostics/pull/135a

 Will update this PR .

**Pull request merged**
