### PR TITLE
Shared code - Applens portal and backend change

### PR DESCRIPTION
**Pull request by crazyxy**
UI for adding new gists.

image

After clicking run.
image

UI for editing existing gists.
image

Code loading gists
image

UI for managing gist version.
image

### CODE REVIEW

**Comment by ShekharGupta1988** [comment]
@crazyxy - Can you paste a screenshot of applens with these changes

**Comment by puneetg1983** [comment]
Hi @crazyxy , do you want the PR to be reviewed or you are still working on it? There are some conflicts so might want to resolve them first ?

**Comment by crazyxy** [comment]
> @crazyxy - Can you paste a screenshot of applens with these changes

Screenshot included.

**Comment by crazyxy** [comment]
> Hi @crazyxy , do you want the PR to be reviewed or you are still working on it? There are some conflicts so might want to resolve them first ?

@puneetg1983 Hi Puneet, conflicts resolved and I am ready for review.

**Pull request merged**
