### PR TITLE
Add Table Filters

### PR DESCRIPTION
**Pull request by XiaoxuHU**
This PR is for extending data-table to add filters and customize column width and visibility.

Along with backend PR, [Add Table Filters #1055](https://github.com/Azure/Azure-AppServices-Diagnostics/pull/649)

image

image

### CODE REVIEW

**Review by michimune — APPROVED** [review]
Thank you!

**Review by ShekharGupta1988 — APPROVED** [review]
Looks good :) Just make sure to run some basic accessibility tests as well.

**Comment by puneetg1983** [comment]
Lovely! Thank you so much for doing this 👍

**Comment by XiaoxuHU** [comment]
> Looks good :) Just make sure to run some basic accessibility tests as well.

Yes, @ShekharGupta1988

**Pull request merged**
